### PR TITLE
Fix naming conventions for actions and formatting fixes

### PR DESCRIPTION
**Pull request by hemant-hc**
This PR introduces:

1. Updated naming conventions  and removed unnecessary action for merged actions .
2. Formatting changes for consistency.

### CODE REVIEW

**Comment by hemant-hc** [comment]
@sneridagh This PR is good to go.

**Comment by hemant-hc** [comment]
I think it would be better to merge PR #21 to avoid merge conflict

**Comment by sneridagh** [comment]
@hemant-hc You need to resolve conflicts now in this one. Are the others depending on the branches also? If they do not, I would base them in main not one after each other.

**Comment by hemant-hc** [comment]
@sneridagh good to go now

**Review by sneridagh — APPROVED** [review]

**Pull request merged**
