### PR TITLE
blueprint of the axios refactor

### PR DESCRIPTION
**Pull request by sneridagh**
@hemant-hc I've been spending the evening working on this. I think it's not worth the effort to maintain the API class, it's a matter of configuring axios correctly. I had problems with the error handling, since react-query wants it to throw if an error occurs, the tests are failing for 404 and all "error" responses. 

Please, continue with it. Let me know what do you think.

### CODE REVIEW

**Comment by sneridagh** [comment]
@hemant-hc while per separated, the requests seems to work well, it seems that two chained tests fail :( No clue still why.

**Comment by sneridagh** [comment]
@hemant-hc ok, so this is it. I think I got it. The tests pass for the content/get

I'd like to see a PR with the complete refactor of the axios, separated from any other thing. Please take this one as blueprint for your PR.

**Comment by sneridagh** [comment]
@hemant-hc I tested also a mutator test too (content/add) and works well. So no CORS problem at all.

EDIT: I fixed the 404 issues, it's true that it complains about a preflight not valid request (404) but it's ok. We can live with it.

**Comment by hemant-hc** [comment]
@sneridagh thanks for the blueprint, I will start working on a new PR now. Also, it seems that introduction of `option.raw` will make the return type complex. The return type would be something like this `{ data: IData, ...otherKeys: IOther } | IData`. We might be able to handle this with typescript somehow based on the raw parameter, but I am not super sure right now.

**Comment by sneridagh** [comment]
I know. For now I see it's not complaining...
I decided to add it as a convenience escape hatch. Mainly for testing and
maybe an upcoming command line utility might be handy.
So default is return data or throw, for direct usage by RQ and then the
escape hatch.
Cheers,

Víctor Fernández de Alba
Github/Twitter: sneridagh

**Pull request closed without merging**
